//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBasedApproached.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeeinfo
    {
        public int Id { get; set; }
        public string EmpName { get; set; }
        public long EmpSalary { get; set; }
    }
}
